module.exports = {
  alertExists: ' - Alert exists already',
  axiosError: 'Error with Axios: ',
  ccAggregate: '&aggregate=1',
  ccHourlyHistApi: 'https://min-api.cryptocompare.com/data/histohour?fsym=',
  ccUSDToSymbol: '&tsym=USD',
  cmcTop100CoinsApi: 'https://api.coinmarketcap.com/v2/ticker/?limit=100&structure=array',
  dataEmpty: 'Data coming back empty: ',
  done: 'Done: ',
  error: 'Error: ',
  googleSheetsApiUrl: 'https://sheets.googleapis.com/v4/spreadsheets/1FU5qgalAYC7gcgypm2qgMe8O-VI8gDsmDdjo6Yr7a_Q/values/A1%3AB?key=AIzaSyCIzT7BqKppc4o9emf03YzO3MZv4qa7bN4',
  mimeTypeJson: 'application/json',
  mongoCSDatabase: 'mongodb://cryptospotlight:12345678abc@ds117848.mlab.com:17848/cryptospotlight',
  noInfoFound: 'No info found',
  noRankingsFound: 'No rankings info found',
  nothingToSee: 'Nothing to see here, carry on',
  numOfAlerts: '# of Alerts: ',
  numOfDocsAffected: '# of affected docs: ',
  numOfRecordsSaved: 'Number of records successfully saved: ',
  USD: 'USD',
};